### ISSUE TITLE
  File "subdover.py", line 258, in <module>

### ISSUE THREAD

**Issue by tushar829** [PushpenderIndia/subdover#3]
Traceback (most recent call last):
  File "subdover.py", line 258, in <module>
    enumSubdomain(arguments.domain)          
  File "subdover.py", line 101, in enumSubdomain
    os.remove(f"{domain}.txt")

**Comment by PushpenderIndia** [comment]
Which OS you are using ? and can you please send the screenshot

**Comment by rijinrij** [comment]
![Screenshot at 2020-09-17 19-40-35](https://user-images.githubusercontent.com/43523195/93482846-ae197e80-f8ef-11ea-89da-09db952e5a26.png)
am on parrot os
Debian 5.7.10-1parrot2 (2020-07-31)

**Comment by PushpenderIndia** [comment]
I think you have not installed **httpx** and **findomain** on your system, I have created a python installer for linux, download subdover again and follow the installation guide for linux

For Windows, you don't have to install **httpx** and **findomain**, as there binary is included in the project

**Comment by tushar829** [comment]
![github](https://user-images.githubusercontent.com/58245340/93559350-2ab66680-f99d-11ea-93b9-0ee9e654ec2f.jpeg)

**Comment by tushar829** [comment]
![github](https://user-images.githubusercontent.com/58245340/93559479-75d07980-f99d-11ea-8932-7fc4196f516f.jpeg)

**Comment by PushpenderIndia** [comment]
Please download the tool again and then use it, you are using older
version, and also install it's dependencies via installer_linux.py

Follow installation guide for linux mentioned in the Readme.md

**Comment by rijinrij** [comment]
httpx is latest version but findomain is missing after install its shows another error 
─[root@parrot]─[/opt/subdover]
└──╼ #python3 subdover.py -l list.txt
		Author: Pushpender Singh  | GitHub: PushpenderIndia

==================================================================
[*] Adding Appropriate Web Protocal to Subdomains using httpx ...
[*] Writing Subdomains in New TXT file ...
Traceback (most recent call last):
  File "subdover.py", line 240, in <module>
    os.rename(arguments.subdomain_list.replace(filename, filename.replace(" ", "_"))+"-httpx.txt", arguments.subdomain_list.replace(filename, filename.replace(" ", "_")))
FileNotFoundError: [Errno 2] No such file or directory: 'list.txt-httpx.txt' -> 'list.txt'

**Comment by tushar829** [comment]
thanks

**Comment by PushpenderIndia** [comment]
> 
> 
> httpx is latest version but findomain is missing after install its shows another error
> ─[root@parrot]─[/opt/subdover]
> └──╼ #python3 subdover.py -l list.txt
> Author: Pushpender Singh | GitHub: PushpenderIndia
> 
> ==================================================================
> [_] Adding Appropriate Web Protocal to Subdomains using httpx ... [_] Writing Subdomains in New TXT file ...
> Traceback (most recent call last):
> File "subdover.py", line 240, in
> os.rename(arguments.subdomain_list.replace(filename, filename.replace(" ", "_"))+"-httpx.txt", arguments.subdomain_list.replace(filename, filename.replace(" ", "_")))
> FileNotFoundError: [Errno 2] No such file or directory: 'list.txt-httpx.txt' -> 'list.txt'

Updated Subdover, now please check it again
